# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:38
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170904_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', DjangoUeditor.models.UEditorField()),
            ],
        ),
    ]
